--Denuncias
INSERT INTO Denuncias VALUES ('DFCV','Asesinato','Estelí',153,138,2023);
INSERT INTO Denuncias VALUES('DFCV','Homicidio','Carazo',68,53,2023);
INSERT INTO Denuncias VALUES ('DFCV','Lesiones','Managua',159,144,2023);
INSERT INTO Denuncias VALUES ('DFCV','Violaciones','Rivas',89,74,2023);						
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Fuerza','RACCN',199,184,2021);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Violencia','Granada',166,151,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Intimidación','Chontales',171,156,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Hurtos','Masaya',107,92,2021);
INSERT INTO Denuncias VALUES ('DFCPO','Estafas','Matagalpa',207,192,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Abigeatos','RACCS',91,76,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Otros Contra el Patrimonio','Nueva Segovia',144,129,2022);
INSERT INTO Denuncias VALUES ('DFCV','Asesinato','Chinandega',94,79,2023);
INSERT INTO Denuncias VALUES ('DFCV','Homicidio','Boaco',112,97,2021);
INSERT INTO Denuncias VALUES ('DFCV','Lesiones','Madriz',216,201,2023);
INSERT INTO Denuncias VALUES ('DFCV','Violaciones','León',208,193,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Fuerza','Río San Juan',125,110,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Violencia','Jinotega',186,171,2023);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Intimidación','Triángulo Minero',114,99,2022);
INSERT INTO Denuncias VALUES ('DFCV','Asesinato','Estelí',115,100,2021);
INSERT INTO Denuncias VALUES ('DFCV','Homicidio','Carazo',201,186,2022);
INSERT INTO Denuncias VALUES ('DFCV','Lesiones','Managua',171,156,2021);
INSERT INTO Denuncias VALUES ('DFCV','Violaciones','Rivas',57,42,2023);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Fuerza','RACCN',217,202,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Violencia','Granada',162,147,2023);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Intimidación','Chontales',61,46,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Hurtos','Masaya',72,57,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Estafas','Matagalpa',198,183,2021);
INSERT INTO Denuncias VALUES ('DFCPO','Abigeatos','RACCS',214,199,2021);
INSERT INTO Denuncias VALUES ('DFCPO','Otros Contra el Patrimonio','Nueva Segovia',141,126,2021);
INSERT INTO Denuncias VALUES ('DFCV','Asesinato','Chinandega',168,153,2021);
INSERT INTO Denuncias VALUES ('DFCV','Homicidio','Boaco',174,159,2023);
INSERT INTO Denuncias VALUES ('DFCV','Lesiones','Madriz',81,66,2022);
INSERT INTO Denuncias VALUES ('DFCV','Violaciones','León',96,81,2021);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Fuerza','Río San Juan',149,134,2021);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Violencia','Jinotega',67,52,2021);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Intimidación','Triángulo Minero',217,202,2023);
INSERT INTO Denuncias VALUES ('DFCV','Asesinato','Estelí',220,205,2021);
INSERT INTO Denuncias VALUES ('DFCV','Homicidio','Carazo',83,68,2022);
INSERT INTO Denuncias VALUES ('DFCV','Lesiones','Managua',88,73,2023);
INSERT INTO Denuncias VALUES ('DFCV','Violaciones','Rivas',132,117,2023);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Fuerza','RACCN',148,133,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Violencia','Granada',185,170,2023);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Intimidación','Chontales',173,158,2021);
INSERT INTO Denuncias VALUES ('DFCPO','Hurtos','Masaya',84,69,2021);
INSERT INTO Denuncias VALUES ('DFCPO','Estafas','Matagalpa',165,150,2021);
INSERT INTO Denuncias VALUES ('DFCPO','Abigeatos','RACCS',207,192,2023);
INSERT INTO Denuncias VALUES ('DFCPO','Otros Contra el Patrimonio','Nueva Segovia',165,150,2023);
INSERT INTO Denuncias VALUES ('DFCV','Asesinato','Chinandega',183,168,2021);
INSERT INTO Denuncias VALUES ('DFCV','Homicidio','Boaco',142,127,2021);
INSERT INTO Denuncias VALUES ('DFCV','Lesiones','Madriz',161,146,2021);
INSERT INTO Denuncias VALUES ('DFCV','Violaciones','León',150,135,2023);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Fuerza','Río San Juan',185,170,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Violencia','Jinotega',86,71,2023);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Intimidación','Triángulo Minero',62,47,2023);
INSERT INTO Denuncias VALUES ('DFCV','Asesinato','Estelí',120,105,2023);
INSERT INTO Denuncias VALUES ('DFCV','Homicidio','Carazo',69,54,2022);
INSERT INTO Denuncias VALUES ('DFCV','Lesiones','Managua',182,167,2021);
INSERT INTO Denuncias VALUES ('DFCV','Violaciones','Rivas',176,161,2021);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Fuerza','RACCN',166,151,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Violencia','Granada',209,194,2023);
INSERT INTO Denuncias VALUES ('DFCPO','Robo Con Intimidación','Chontales',93,78,2023);
INSERT INTO Denuncias VALUES ('DFCPO','Hurtos','Masaya',117,102,2022);
INSERT INTO Denuncias VALUES ('DFCPO','Estafas','Matagalpa',208,193,2023);
INSERT INTO Denuncias VALUES ('DFCPO','Abigeatos','RACCS',53,38,2021);
INSERT INTO Denuncias VALUES ('DFCPO','Otros Contra el Patrimonio','Nueva Segovia',72,57,2022);
INSERT INTO Denuncias VALUES ('DFCV','Asesinato','Chinandega',94,79,2021);
GO;

--MallCustomers

INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 19, 15, 39);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 21, 15, 81);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 20, 16, 6);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 23, 16, 77);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 31, 17, 40);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 22, 17, 76);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 35, 18, 6);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 23, 18, 94);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 64, 19, 3);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 30, 19, 72);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 67, 19, 14);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 35, 19, 99);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 58, 20, 15);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 24, 20, 77);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 37, 20, 13);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 22, 20, 79);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 35, 21, 35);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 20, 21, 66);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 52, 23, 29);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 35, 23, 98);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 35, 24, 35);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 25, 24, 73);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 46, 25, 5);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 31, 25, 73);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 54, 28, 14);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 29, 28, 82);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 45, 28, 32);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 35, 28, 61);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 40, 29, 31);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 23, 29, 87);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 60, 30, 4);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 21, 30, 73);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 53, 33, 4);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 18, 33, 92);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 49, 33, 14);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 21, 33, 81);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 42, 34, 17);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 30, 34, 73);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 36, 37, 26);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 20, 37, 75);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 65, 38, 35);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 24, 38, 92);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 48, 39, 36);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 31, 39, 61);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 49, 39, 28);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 24, 39, 65);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 50, 40, 55);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 27, 40, 47);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 29, 40, 42);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 31, 40, 42);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 49, 42, 52);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 33, 42, 60);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 31, 43, 54);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 59, 43, 60);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 50, 43, 45);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 47, 43, 41);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 51, 44, 50);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 69, 44, 46);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 27, 46, 51);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 53, 46, 46);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 70, 46, 56);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 19, 46, 55);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 67, 47, 52);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 54, 47, 59);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 63, 48, 51);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 18, 48, 59);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 43, 48, 50);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 68, 48, 48);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 19, 48, 59);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 32, 48, 47);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 70, 49, 55);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 47, 49, 42);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 60, 50, 49);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 60, 50, 56);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 59, 54, 47);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 26, 54, 54);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 45, 54, 53);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 40, 54, 48);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 23, 54, 52);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 49, 54, 42);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 57, 54, 51);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 38, 54, 55);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 67, 54, 41);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 46, 54, 44);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 21, 54, 57);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 48, 54, 46);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 55, 57, 58);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 22, 57, 55);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 34, 58, 60);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 50, 58, 46);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 68, 59, 55);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 18, 59, 41);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 48, 60, 49);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 40, 60, 40);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 32, 60, 42);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 24, 60, 52);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 47, 60, 47);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 27, 60, 50);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 48, 61, 42);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 20, 61, 49);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 23, 62, 41);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 49, 62, 48);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 67, 62, 59);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 26, 62, 55);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 49, 62, 56);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 21, 62, 42);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 66, 63, 50);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 54, 63, 46);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 68, 63, 43);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 66, 63, 48);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 65, 63, 52);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 19, 63, 54);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 38, 64, 42);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 19, 64, 46);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 18, 65, 48);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 19, 65, 50);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 63, 65, 43);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 49, 65, 59);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 51, 67, 43);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 50, 67, 57);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 27, 67, 56);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 38, 67, 40);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 40, 69, 58);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 39, 69, 91);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 23, 70, 29);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 31, 70, 77);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 43, 71, 35);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 40, 71, 95);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 59, 71, 11);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 38, 71, 75);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 47, 71, 9);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 39, 71, 75);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 25, 72, 34);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 31, 72, 71);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 20, 73, 5);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 29, 73, 88);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 44, 73, 7);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 32, 73, 73);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 19, 74, 10);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 35, 74, 72);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 57, 75, 5);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 32, 75, 93);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 28, 76, 40);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 32, 76, 87);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 25, 77, 12);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 28, 77, 97);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 48, 77, 36);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 32, 77, 74);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 34, 78, 22);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 34, 78, 90);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 43, 78, 17);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 39, 78, 88);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 44, 78, 20);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 38, 78, 76);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 47, 78, 16);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 27, 78, 89);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 37, 78, 1);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 30, 78, 78);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 34, 78, 1);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 30, 78, 73);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 56, 79, 35);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 29, 79, 83);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 19, 81, 5);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 31, 81, 93);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 50, 85, 26);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 36, 85, 75);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 42, 86, 20);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 33, 86, 95);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 36, 87, 27);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 32, 87, 63);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 40, 87, 13);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 28, 87, 75);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 36, 87, 10);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 36, 87, 92);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 52, 88, 13);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 30, 88, 86);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 58, 88, 15);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 27, 88, 69);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 59, 93, 14);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 35, 93, 90);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 37, 97, 32);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 32, 97, 86);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 46, 98, 15);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 29, 98, 88);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 41, 99, 39);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 30, 99, 97);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 54, 101, 24);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 28, 101, 68);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 41, 103, 17);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 36, 103, 85);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 34, 103, 23);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 32, 103, 69);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 33, 113, 8);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 38, 113, 91);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 47, 120, 16);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 35, 120, 79);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Female', 45, 126, 28);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 32, 126, 74);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 32, 137, 18);
INSERT INTO MallCustomers (Gender, Age, AnnualIncome, SpendingScore) VALUES ('Male', 30, 137, 83);
GO;