//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIconMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MallCustomer
    {
        public int Id { get; set; }
        public string Gender { get; set; }
        public short Age { get; set; }
        public short AnnualIncome { get; set; }
        public short SpendingScore { get; set; }
    }
}
